### ISSUE TITLE
Release Version

### ISSUE THREAD

**Issue by megawac** [caolan/async#842]
Probably time for a version. API changes I've identified:

- [x] Asyncify promises https://github.com/caolan/async/pull/840
- [x] Add filter and reject limit https://github.com/caolan/async/pull/836
  - [x] documentation
- [x] Add some and every limit #828 (needs docs)
  - [x] Some and every short circuit early #828
  - [x] documentation
- [x] Improve detection of global script https://github.com/caolan/async/pull/804 enabling use in WebWorkers
- [x] `whilst` now called with args to iterator https://github.com/caolan/async/pull/823
- [x] `during` now gets called with args to iterator https://github.com/caolan/async/pull/824
- [x] Add detect limit https://github.com/caolan/async/pull/829
  - [x] Detect short circuits when item is found #829
  - [x] documentation
- [x] Major code simplifications
- [x] Significant optimizations aplenty

Size comparision of minified file `v1.3.0...master`

```sh
$ gzip -c dist/async.min.js | wc -c                                                                                                                
4103
$ gzip -c lib/async.min.js | wc -c                                                                                                                 
4125

$ wc -c lib/async.min.js 
12059 lib/async.min.js
$ wc -c dist/async.min.js                                                                                                                          
12517
```

/cc @caolan @aearly

**Comment by aearly** [comment]
Yep :+1:  probably get 1.4.0 out this weekend.

**Comment by kobezzza** [comment]
:+1:

**Comment by megawac** [comment]
Should be good to go @aearly anything else to do?

/cc @caolan @beaugunderson

**Comment by aearly** [comment]
We just need to summarize what happened in `CHANGELOG.md`, then we're good to go.

**Comment by megawac** [comment]
So essentially copy paste the op comment to changelog?

**Comment by aearly** [comment]
Yep, we're good to go.

**Comment by megawac** [comment]
Done :fireworks:

**Comment by aearly** [comment]
:tada:
